"""
Step 4: Export training data in S2DD format.

Splits the annotated TCR data by fold:
  - Train (folds 0-2): positives only (binder=1.0)
  - Validation (fold 3): positives + 5:1 epitope-shuffled negatives
  - Test (fold 4): positives + 5:1 epitope-shuffled negatives

Negatives are generated by cross-joining CDR features with mismatched
epitope+MHC contact features, ensuring the paired epitope differs.

Input:
  - <input_dir>/03_tcrs_with_features.tsv

Output:
  - <output_dir>/train_data.csv
  - <output_dir>/validation_data.csv
  - <output_dir>/test_data.csv
"""

import argparse
from pathlib import Path

import polars as pl

NEG_RATIO = 5

JQ_COLUMNS = [
    "epitope",
    "cdr1_a",
    "cdr2_a",
    "cdr3_a",
    "cdr1_b",
    "cdr2_b",
    "cdr3_b",
    "contact1",
    "contact2",
    "pseudo_sequence",
    "binder",
]

REQUIRED_COLS = [
    "epitope",
    "cdr1_a",
    "cdr2_a",
    "cdr3_a",
    "cdr1_b",
    "cdr2_b",
    "cdr3_b",
    "contact1",
    "contact2",
    "pseudo_sequence",
]


def filter_complete_rows(df: pl.DataFrame) -> pl.DataFrame:
    """Remove rows with any null in required columns."""
    return df.filter(
        pl.all_horizontal(pl.col(REQUIRED_COLS).is_not_null())
    )


def generate_shuffled_negatives(
    positives: pl.DataFrame,
    neg_ratio: int = NEG_RATIO,
    seed: int = 42,
) -> pl.DataFrame:
    """Generate negatives by pairing CDRs with mismatched epitope+MHC contacts.

    Matches notebook 6 (notebooks/6_sf_data_aug_shuffle.ipynb,
    `validation_dataset_negatives` and `test_dataset_negatives` cells).
    Cross-joins CDRs and MHCs, filters to mismatched epitopes, samples
    `neg_ratio:1`. Does NOT anti-join against the full positive set —
    this matches the notebook's behavior. Some sampled (CDR, epitope')
    rows may collide with known positives elsewhere in the dataset; the
    notebook accepted this label noise.
    """
    cdr_cols = [c for c in positives.columns if c.startswith("cdr")]
    mhc_cols = ["epitope", "contact1", "contact2", "pseudo_sequence"]

    cdrs = positives.select(cdr_cols + ["epitope"])
    mhcs = positives.select(mhc_cols)

    candidates = (
        cdrs.join(mhcs, how="cross", suffix="_neg")
        .filter(pl.col("epitope") != pl.col("epitope_neg"))
        .select(
            pl.col("epitope_neg").alias("epitope"),
            *[pl.col(c) for c in cdr_cols],
            "contact1",
            "contact2",
            "pseudo_sequence",
            pl.lit(0.0).alias("binder"),
        )
    )

    target = positives.height * neg_ratio
    return candidates.sample(n=target, seed=seed)


def main() -> None:
    parser = argparse.ArgumentParser(description="Step 4: Export S2DD format")
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    input_path = args.input_dir / "03_tcrs_with_features.tsv"
    df = pl.read_csv(input_path, separator="\t")
    print(f"Loaded {df.height:,} rows from {input_path}")

    # Filter to rows with all required JQ columns non-null
    df = filter_complete_rows(df)
    print(f"After null filter: {df.height:,} rows")

    # Strip IMGT flanking residues conditionally: drop leading C only if present,
    # drop trailing F/W only if present. The notebook's CDR3s came from ANARCI
    # which always produced compliant sequences, so it could strip unconditionally.
    # The port reads from VDJdb/McPAS where pyrepseq passes through a small
    # number of non-conforming CDR3s; an unconditional slice(1, len-2) silently
    # corrupts them.
    df = df.with_columns(
        pl.when(pl.col("cdr3_a").str.starts_with("C"))
        .then(pl.col("cdr3_a").str.slice(1))
        .otherwise(pl.col("cdr3_a"))
        .alias("cdr3_a"),
        pl.when(pl.col("cdr3_b").str.starts_with("C"))
        .then(pl.col("cdr3_b").str.slice(1))
        .otherwise(pl.col("cdr3_b"))
        .alias("cdr3_b"),
    ).with_columns(
        pl.when(pl.col("cdr3_a").str.contains(r"[FW]$"))
        .then(pl.col("cdr3_a").str.slice(0, pl.col("cdr3_a").str.len_chars() - 1))
        .otherwise(pl.col("cdr3_a"))
        .alias("cdr3_a"),
        pl.when(pl.col("cdr3_b").str.contains(r"[FW]$"))
        .then(pl.col("cdr3_b").str.slice(0, pl.col("cdr3_b").str.len_chars() - 1))
        .otherwise(pl.col("cdr3_b"))
        .alias("cdr3_b"),
    )

    # === TRAIN: folds 0-2, positives only ===
    train_positives = (
        df.filter(pl.col("fold").is_in([0, 1, 2]))
        .select(JQ_COLUMNS[:-1] + [pl.lit(1.0).alias("binder")])
    )
    train_positives.write_csv(args.output_dir / "train_data.csv")
    print(f"\nTrain: {train_positives.height:,} positives (folds 0-2)")

    # === VALIDATION: fold 3, positives + 5:1 shuffled negatives ===
    val_positives = (
        df.filter(pl.col("fold") == 3)
        .select(JQ_COLUMNS[:-1] + [pl.lit(1.0).alias("binder")])
    )
    val_negatives = generate_shuffled_negatives(val_positives, seed=args.seed)
    val_export = pl.concat([val_positives, val_negatives]).sample(
        n=val_positives.height * (1 + NEG_RATIO), seed=args.seed
    )
    val_export.write_csv(args.output_dir / "validation_data.csv")
    print(f"Val:   {val_positives.height:,} pos + {val_negatives.height:,} neg = {val_export.height:,} total (fold 3)")

    # === TEST: fold 4, positives + 5:1 shuffled negatives ===
    test_positives = (
        df.filter(pl.col("fold") == 4)
        .select(JQ_COLUMNS[:-1] + [pl.lit(1.0).alias("binder")])
    )
    test_negatives = generate_shuffled_negatives(test_positives, seed=args.seed)
    test_export = pl.concat([test_positives, test_negatives]).sample(
        fraction=1.0, seed=args.seed
    )
    test_export.write_csv(args.output_dir / "test_data.csv")
    print(f"Test:  {test_positives.height:,} pos + {test_negatives.height:,} neg = {test_export.height:,} total (fold 4)")


if __name__ == "__main__":
    main()
