#!/usr/bin/env python3
"""Fig 4 method comparison boxplots — reads from audit CSV (CT+CV combined).

Two panel types:
  1. Absolute error boxplots (MAE per point)
  2. Correlation boxplots (r per model, showing ranking accuracy)

Data source: audit_baseline_comparison_128_results.csv (CT+CV, pool-then-split)
  - Generated by: dev-only audit (CSV committed at INPUT_DIR/results/fig4_audit/)
  - 3 methods: M-CBPE, PAPE, S2DD — each uses ONLY its own features
  - min_per_epitope=128, bin_strategy='subset' for S2DD

Panels:
  - fig4_boxplot_subset_type_aucroc/ap (error + correlation)
  - fig4_boxplot_model_aucroc/ap (error)
  - fig4_boxplot_seen_unseen_aucroc/ap (error)
"""
import os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, wilcoxon

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Self-contained path anchors (BUILD_PLAN §1+§5.2)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _paths import INPUT_DIR, OUTPUT_DIR, CACHE_DIR, FIG_DIR  # also adds CaliPPer/ to sys.path
from style_config import apply_publication_style, FONT_LABEL, FONT_TICK, FONT_LEGEND, DPI
sys.path.insert(0, os.path.join(INPUT_DIR, 'Manuscript', 'designed_figures', 'panels'))
from dist_config import DIST_TYPE, DIST_SUBDIR
apply_publication_style()

_FIG_DIR = os.path.join(FIG_DIR, 'fig4')
OUT_DIR = os.path.join(_FIG_DIR, DIST_SUBDIR[DIST_TYPE])
os.makedirs(OUT_DIR, exist_ok=True)

METHODS = ['M-CBPE', 'PAPE', 'CaliPPer']
COLS = ['mcbpe', 'pape', 's2dd']
COLORS = ['#95a5a6', '#3498db', '#e67e22']  # grey, blue, orange (ours)
MODELS = ['nettcr', 'atm_tcr', 'blosum_rf', 'ergo_ii', 'tcrbert']
MODEL_DISPLAY = {'nettcr': 'NetTCR', 'atm_tcr': 'ATM-TCR', 'blosum_rf': 'BLOSUM-RF',
                 'ergo_ii': 'ERGO-II', 'tcrbert': 'TCR-BERT'}

# Load audit results (CT+CV epitope, all 3 methods)
AUDIT_CSV = os.path.join(INPUT_DIR, 'results', 'fig4_audit', f'audit_baseline_comparison_128_{DIST_TYPE}_results.csv')
audit = pd.read_csv(AUDIT_CSV)
print(f"Loaded audit CSV: {len(audit)} rows, splits={audit['split'].value_counts().to_dict()}")

# Load cache for distance results (S2DD only)
CACHE = os.path.join(INPUT_DIR, 'results', 'fig3_fig4_tcr_cache')


def make_error_boxplot(group_data, group_labels, group_r, mdisp, title, filename):
    """Boxplot of absolute error + r annotation."""
    n_groups = len(group_labels)
    n_methods = len(COLS)
    width = 0.25

    pw = max(4.0, n_groups * 1.5 + 1)
    fig, ax = plt.subplots(1, 1, figsize=(pw, 3.5))

    for j, (mc, mn, clr) in enumerate(zip(COLS, METHODS, COLORS)):
        bp_data = [np.array(group_data[i].get(mc, [0])) for i in range(n_groups)]
        pos = np.arange(n_groups) + (j - 1) * width
        bp = ax.boxplot(bp_data, positions=pos, widths=width * 0.8,
                        patch_artist=True, showfliers=False, notch=True)
        for patch in bp['boxes']:
            patch.set_facecolor(clr); patch.set_alpha(0.7)
        for med in bp['medians']:
            med.set_color('black'); med.set_linewidth(1.2)
        for k, d in enumerate(bp_data):
            jitter = np.random.default_rng(42).uniform(-width * 0.10, width * 0.10, len(d))
            ax.scatter(pos[k] + jitter, d, c=clr, s=3, alpha=0.3, zorder=4, linewidths=0)

    # r annotations under each group
    for i in range(n_groups):
        parts = []
        for mc, mn, clr in zip(COLS, METHODS, COLORS):
            r_val = group_r[i].get(mc)
            if r_val is not None:
                parts.append(f'{mn}={r_val:.2f}')
        if parts:
            ax.text(i, -0.07, 'r: ' + '  '.join(parts), ha='center', va='top',
                    fontsize=FONT_LEGEND - 3, color='#444444',
                    transform=ax.get_xaxis_transform())

    for i in range(n_groups):
        n_pts = len(list(group_data[i].values())[0]) if group_data[i] else 0
        ax.text(i, -0.02, f'n={n_pts}', ha='center', va='top',
                fontsize=FONT_LEGEND - 2, color='gray', transform=ax.get_xaxis_transform())

    ax.set_xticks(np.arange(n_groups))
    ax.set_xticklabels(group_labels, fontsize=FONT_TICK, rotation=25, ha='right')
    ax.set_ylabel('Absolute prediction error', fontsize=FONT_LABEL - 2)
    ax.set_title(title, fontsize=FONT_LABEL - 1, fontweight='bold')
    ax.grid(axis='y', alpha=0.3); ax.grid(axis='x', visible=False); ax.set_axisbelow(True)

    handles = [plt.Rectangle((0, 0), 1, 1, facecolor=c, alpha=0.7) for c in COLORS]
    ax.legend(handles, METHODS, fontsize=FONT_LEGEND - 1, loc='upper right', framealpha=0.9)

    fig.savefig(os.path.join(OUT_DIR, filename + '.png'), dpi=DPI, bbox_inches='tight')
    fig.savefig(os.path.join(OUT_DIR, filename + '.pdf'), dpi=DPI, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {filename}")


def make_correlation_boxplot(group_r_per_model, group_labels, mdisp, title, filename):
    """Boxplot of per-model correlation (r) — shows ranking accuracy.
    figsize matches Panel H (fig4_subset_correlation_boxplot) for grid alignment."""
    n_groups = len(group_labels)
    width = 0.25

    fig, ax = plt.subplots(1, 1, figsize=(3.5, 3.0))

    for j, (mc, mn, clr) in enumerate(zip(COLS, METHODS, COLORS)):
        bp_data = [np.array(group_r_per_model[i].get(mc, [0])) for i in range(n_groups)]
        pos = np.arange(n_groups) + (j - 1) * width
        bp = ax.boxplot(bp_data, positions=pos, widths=width * 0.8,
                        patch_artist=True, showfliers=False, notch=True)
        for patch in bp['boxes']:
            patch.set_facecolor(clr); patch.set_alpha(0.7)
        for med in bp['medians']:
            med.set_color('black'); med.set_linewidth(1.2)
        # Strip plot
        for k, d in enumerate(bp_data):
            jitter = np.random.default_rng(42).uniform(-width * 0.10, width * 0.10, len(d))
            ax.scatter(pos[k] + jitter, d, c=clr, s=15, alpha=0.7, zorder=4,
                       linewidths=0.5, edgecolors='white')

    for i in range(n_groups):
        n_models = len(list(group_r_per_model[i].values())[0]) if group_r_per_model[i] else 0
        ax.text(i, -0.02, f'{n_models} models', ha='center', va='top',
                fontsize=FONT_LEGEND - 2, color='gray', transform=ax.get_xaxis_transform())

    ax.set_xticks(np.arange(n_groups))
    ax.set_xticklabels(group_labels, fontsize=FONT_TICK, rotation=25, ha='right')
    ax.set_ylabel('Correlation (r)', fontsize=FONT_LABEL - 2)
    ax.set_title(title, fontsize=FONT_LABEL - 1, fontweight='bold')
    ax.axhline(y=0, color='black', linewidth=0.5, linestyle='--', alpha=0.3)
    ax.grid(axis='y', alpha=0.3); ax.grid(axis='x', visible=False); ax.set_axisbelow(True)

    handles = [plt.Rectangle((0, 0), 1, 1, facecolor=c, alpha=0.7) for c in COLORS]
    ax.legend(handles, METHODS, fontsize=FONT_LEGEND - 1, loc='lower right', framealpha=0.9)

    fig.savefig(os.path.join(OUT_DIR, filename + '.png'), dpi=DPI, bbox_inches='tight')
    fig.savefig(os.path.join(OUT_DIR, filename + '.pdf'), dpi=DPI, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {filename}")


# ══════════════════════════════════════
# Generate panels
# ══════════════════════════════════════
print("\nGenerating boxplot panels (CT+CV combined)...")

for metric_col, mdisp in [('aucroc', 'AUROC'), ('ap', 'AP')]:
    # Filter by metric if column exists
    if 'metric' in audit.columns:
        df = audit[audit['metric'] == metric_col].copy()
    else:
        df = audit.copy()  # legacy: only AUROC
    print(f"  {mdisp}: {len(df)} rows after metric filter")

    # ── Panel 1: by subset type (both from audit CSV) ──
    group_data = []
    group_r_vals = []
    group_r_pm = []
    for strategy in ['epitope', 'distance']:
        strat_df = df[df['strategy'] == strategy] if 'strategy' in df.columns else df
        errs = {}
        r_vals = {}
        r_per_model = {}
        for mc in COLS:
            valid = strat_df.dropna(subset=[mc, 'actual'])
            errs[mc] = np.abs(valid[mc] - valid['actual']).tolist()
            if len(valid) >= 3:
                r, _ = pearsonr(valid[mc], valid['actual'])
                r_vals[mc] = r
            model_rs = []
            for model in MODELS:
                sub = valid[valid['model'] == model]
                if len(sub) >= 3:
                    r, _ = pearsonr(sub[mc], sub['actual'])
                    model_rs.append(r)
            r_per_model[mc] = model_rs
        group_data.append(errs)
        group_r_vals.append(r_vals)
        group_r_pm.append(r_per_model)

    make_error_boxplot(group_data, ['Epitope splitting', 'Distance splitting'],
                       group_r_vals, mdisp,
                       f'{mdisp} prediction error — subset type (CT+CV)',
                       f'fig4_boxplot_subset_type_{metric_col}')
    make_correlation_boxplot(group_r_pm, ['Epitope splitting', 'Distance splitting'],
                             mdisp,
                             f'{mdisp} subset-prediction (CT+CV)',
                             f'fig4_boxplot_correlation_subset_type_{metric_col}')

    # ── Panel 2: by model (error — epitope+distance combined) ──
    group_data = []
    group_r_vals = []
    for model in MODELS:
        errs = {}
        r_vals = {}
        for mc in COLS:
            sub = df[(df['model'] == model)].dropna(subset=[mc, 'actual'])
            errs[mc] = np.abs(sub[mc] - sub['actual']).tolist()
            if len(sub) >= 3:
                r, _ = pearsonr(sub[mc], sub['actual'])
                r_vals[mc] = r
        group_data.append(errs)
        group_r_vals.append(r_vals)
    make_error_boxplot(group_data, [MODEL_DISPLAY[m] for m in MODELS],
                       group_r_vals, mdisp,
                       f'{mdisp} prediction error — by model (CT+CV)',
                       f'fig4_boxplot_model_{metric_col}')

    # ── Panel 2b: by model (correlation per strategy×split) ──
    group_r_pm = []
    for model in MODELS:
        model_rs = {}
        for mc in COLS:
            rs = []
            for strategy in ['epitope', 'distance']:
                for split in ['CT', 'CV']:
                    sub = df[(df['model'] == model) & (df['split'] == split)]
                    if 'strategy' in sub.columns:
                        sub = sub[sub['strategy'] == strategy]
                    sub = sub.dropna(subset=[mc, 'actual'])
                    if len(sub) >= 3:
                        r, _ = pearsonr(sub[mc], sub['actual'])
                        rs.append(r)
            model_rs[mc] = rs
        group_r_pm.append(model_rs)
    make_correlation_boxplot(group_r_pm, [MODEL_DISPLAY[m] for m in MODELS],
                             mdisp,
                             f'{mdisp} prediction correlation — by model (CT+CV)',
                             f'fig4_boxplot_correlation_model_{metric_col}')

    # ── Panel 3: seen vs unseen (error) ──
    group_data = []
    group_r_vals = []
    for label in ['seen', 'unseen', 'cv']:
        errs = {}
        r_vals = {}
        for mc in COLS:
            sub = df[df['seen'] == label].dropna(subset=[mc, 'actual'])
            errs[mc] = np.abs(sub[mc] - sub['actual']).tolist()
            if len(sub) >= 3:
                r, _ = pearsonr(sub[mc], sub['actual'])
                r_vals[mc] = r
        group_data.append(errs)
        group_r_vals.append(r_vals)
    make_error_boxplot(group_data, ['CT seen', 'CT unseen', 'CV'],
                       group_r_vals, mdisp,
                       f'{mdisp} prediction error — seen/unseen/CV',
                       f'fig4_boxplot_seen_unseen_{metric_col}')

    # ── Panel 3b: seen vs unseen (correlation per model) ──
    group_r_pm = []
    for label in ['seen', 'unseen', 'cv']:
        cat_rs = {}
        for mc in COLS:
            rs = []
            for model in MODELS:
                sub = df[(df['seen'] == label) & (df['model'] == model)].dropna(subset=[mc, 'actual'])
                if len(sub) >= 3:
                    r, _ = pearsonr(sub[mc], sub['actual'])
                    rs.append(r)
            cat_rs[mc] = rs
        group_r_pm.append(cat_rs)
    make_correlation_boxplot(group_r_pm, ['CT seen', 'CT unseen', 'CV'],
                             mdisp,
                             f'{mdisp} prediction correlation — seen/unseen/CV',
                             f'fig4_boxplot_correlation_seen_unseen_{metric_col}')

print("\nDone.")
