#!/usr/bin/env python3
"""Fig 4 BCR: 40 scatter panels matching TCR format exactly.

Same layout as TCR panels:
  - 5 models × 2 strategies (distance, antigen) × 2 metrics (AUROC, AP) × 2 vis types = 40
  - source_scatter: CV = hollow squares (color by fold), CT = filled circles (color by domain source)
  - property_scatter: size = n, color = prevalence
  - predicted vs actual, square aspect, r/MAE/n stats

Reads from: results/fig3_fig4_bcr_cache/bcr_fig4_fold4cal_{ct|cv}_{distance|antigen}_{metric}.csv
Generated by: cache_bcr_fig4_fold4cal.py
"""
import os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Self-contained path anchors (BUILD_PLAN §1+§5.2)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _paths import INPUT_DIR, OUTPUT_DIR, CACHE_DIR, FIG_DIR  # also adds CaliPPer/ to sys.path
from style_config import apply_publication_style, DPI, FONT_LABEL, FONT_TICK, FONT_LEGEND

apply_publication_style()

RESULTS = os.path.join(INPUT_DIR, 'results')
BCR_CACHE = os.path.join(RESULTS, 'fig3_fig4_bcr_cache')
OUT_DIR = os.path.join(SCRIPT_DIR, '..', 'BCR_panels')
os.makedirs(OUT_DIR, exist_ok=True)

MODELS = ['xbcr', 'deepaai', 'mambaaai', 'mint', 'rleaai']
MODEL_DISPLAY = {'xbcr': 'XBCR-net', 'deepaai': 'DeepAAI', 'mambaaai': 'MambaAAI',
                  'mint': 'MINT', 'rleaai': 'RLEAAI'}
STRATEGIES = ['distance', 'antigen']
STRATEGY_DISP = {'distance': 'Distance splitting', 'antigen': 'Antigen splitting'}
METRICS = ['aucroc', 'ap']
METRIC_DISP = {'aucroc': 'AUROC', 'ap': 'AP'}

# Colors matching TCR style
CV_COLORS = {0: '#1f77b4', 1: '#ff7f0e', 2: '#2ca02c', 3: '#d62728', 4: '#9467bd'}
CT_COLORS = {
    'sars': '#e74c3c', 'flu': '#3498db',
}
CT_MARKERS = {'sars': 'o', 'flu': 's'}

PW, PH = 3.0, 3.0


def load_cached(split, strategy, metric):
    f = os.path.join(BCR_CACHE, f'bcr_fig4_fold4cal_{split}_{strategy}_{metric}.csv')
    if os.path.exists(f):
        return pd.read_csv(f)
    return None


def plot_source_scatter(ax, ct_df, cv_df, model, metric):
    """Scatter colored by source, matching TCR format."""
    all_x, all_y = [], []

    # CV points — hollow squares by fold
    if cv_df is not None:
        for fold in sorted(cv_df['fold'].unique()):
            sub = cv_df[cv_df['fold'] == fold]
            ax.scatter(sub['actual'], sub['predicted'],
                       facecolors='none', edgecolors=CV_COLORS.get(fold, '#aaa'),
                       marker='s', s=22, linewidths=0.8,
                       alpha=0.7, label=f'CV F{fold}', zorder=2)
            all_x.extend(sub['actual']); all_y.extend(sub['predicted'])

    # CT points — filled, by domain
    if ct_df is not None:
        for _, row in ct_df.iterrows():
            src = row['source']
            domain = 'flu' if 'flu' in src else 'sars'
            # Collect for batch plotting below
        # Batch by domain
        for domain in ['sars', 'flu']:
            sub = ct_df[ct_df['source'].str.contains(domain if domain == 'flu' else 'sars')]
            if len(sub) == 0:
                continue
            ax.scatter(sub['actual'], sub['predicted'],
                       c=CT_COLORS.get(domain, '#aaa'),
                       marker=CT_MARKERS.get(domain, 'o'),
                       s=30, alpha=0.8, edgecolors='white', linewidths=0.5,
                       label=f'CT {domain.upper()}', zorder=3)
            all_x.extend(sub['actual']); all_y.extend(sub['predicted'])

    _finish_scatter(ax, np.array(all_x), np.array(all_y), metric)
    ax.legend(fontsize=FONT_LEGEND - 3, loc='upper left', bbox_to_anchor=(1.02, 1.0),
              framealpha=0.85, handletextpad=0.3, borderpad=0.3, labelspacing=0.2,
              borderaxespad=0)


def plot_property_scatter(ax, ct_df, cv_df, metric):
    """Scatter: size = n, color = prevalence, matching TCR format."""
    all_x, all_y, all_prev, all_n = [], [], [], []

    for df in [cv_df, ct_df]:
        if df is None:
            continue
        all_x.extend(df['actual']); all_y.extend(df['predicted'])
        all_prev.extend(df['prevalence']); all_n.extend(df['n'])

    if not all_x:
        return

    all_x, all_y = np.array(all_x), np.array(all_y)
    all_prev, all_n = np.array(all_prev), np.array(all_n, dtype=float)

    n_min, n_max = all_n.min(), all_n.max()
    if n_max > n_min:
        sizes = 12 + 100 * (all_n - n_min) / (n_max - n_min)
    else:
        sizes = np.full_like(all_n, 30)

    sc = ax.scatter(all_x, all_y, c=all_prev, cmap='coolwarm',
                    vmin=0, vmax=1, s=sizes,
                    alpha=0.7, edgecolors='white', linewidths=0.5, zorder=3)
    cbar = plt.colorbar(sc, ax=ax, shrink=0.65, pad=0.02)
    cbar.set_label('Class prevalence', fontsize=FONT_LEGEND - 2)
    cbar.ax.tick_params(labelsize=FONT_LEGEND - 3)

    _finish_scatter(ax, all_x, all_y, metric)

    n_mid = (n_min + n_max) / 2
    for n_val in [n_min, n_mid, n_max]:
        s = 12 + 100 * (n_val - n_min) / (n_max - n_min + 1e-9)
        ax.scatter([], [], c='gray', s=s, alpha=0.5, label=f'n={int(n_val)}')
    ax.legend(fontsize=FONT_LEGEND - 3, loc='lower right', framealpha=0.85,
              handletextpad=0.2, borderpad=0.2, labelspacing=0.2)


def _finish_scatter(ax, all_x, all_y, metric):
    if len(all_x) < 3:
        return
    pad = 0.03
    lo = min(all_x.min(), all_y.min()) - pad
    hi = max(all_x.max(), all_y.max()) + pad
    ax.plot([lo, hi], [lo, hi], 'k--', linewidth=0.5, alpha=0.3)
    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_aspect('equal', adjustable='box')
    ax.grid(False)
    r, p = pearsonr(all_x, all_y)
    mae = np.mean(np.abs(all_x - all_y))
    n = len(all_x)
    p_str = 'p < 0.001' if p < 0.001 else f'p = {p:.3f}'
    ax.text(0.05, 0.95, f'r = {r:.2f}, {p_str}\nMAE = {mae:.3f}, n = {n}',
            transform=ax.transAxes, fontsize=FONT_TICK - 2, va='top',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                      edgecolor='#ccc', alpha=0.9, linewidth=0.3))
    mdisp = METRIC_DISP.get(metric, metric)
    ax.set_xlabel(f'Actual {mdisp}', fontsize=FONT_LABEL - 2)
    ax.set_ylabel(f'Predicted {mdisp}', fontsize=FONT_LABEL - 2)


# ── Generate all 40 panels ──
print("Generating 40 BCR scatter panels (TCR format)...")
count = 0
for model in MODELS:
    for strategy in STRATEGIES:
        for metric in METRICS:
            ct_all = load_cached('ct', strategy, metric)
            cv_all = load_cached('cv', strategy, metric)
            ct_df = ct_all[ct_all['model'] == model] if ct_all is not None and 'model' in ct_all.columns else None
            cv_df = cv_all[cv_all['model'] == model] if cv_all is not None and 'model' in cv_all.columns else None

            if (ct_df is None or len(ct_df) == 0) and (cv_df is None or len(cv_df) == 0):
                print(f"  SKIP {model} {strategy} {metric} — no data")
                continue

            mdisp = METRIC_DISP[metric]
            sdisp = STRATEGY_DISP[strategy]
            model_disp = MODEL_DISPLAY[model]

            for vis in ['source', 'property']:
                fig, ax = plt.subplots(1, 1, figsize=(PW, PH))
                if vis == 'source':
                    plot_source_scatter(ax, ct_df, cv_df, model, metric)
                else:
                    plot_property_scatter(ax, ct_df, cv_df, metric)

                ax.set_title(f'{model_disp}: {sdisp.lower()}, {mdisp}',
                             fontsize=FONT_TICK, fontweight='bold')

                out = os.path.join(OUT_DIR,
                    f'fig4_bcr_{vis}_{strategy}_{metric}_{model}')
                fig.savefig(out + '.png', dpi=DPI, bbox_inches='tight')
                fig.savefig(out + '.pdf', dpi=DPI, bbox_inches='tight')
                plt.close(fig)
                count += 1

print(f"Done: {count} BCR scatter panels saved to {OUT_DIR}")
