#!/usr/bin/env python3
"""fig2.py — Figure 2 driver: Degradation across 10 models.

Orchestrates panel-script invocations and extracts the canonical numerical
values that the manuscript claims for Figure 2. Writes:

  - {out_data}/fig2_values.csv  — numerical claims (verified by verify.sh)
  - {out_fig}/fig2.pdf           — rendered figure (cosmetic; not verified)

Panel scripts orchestrated (in `reproduce/scripts/fig2/`):
  - cache_bcr_fig2_data.py
  - compute_bcr_blosum_heavy_naive.py
  - compute_bcr_esm2_heavy_naive.py
  - compute_bcr_esm2_s2dd.py
  - compute_blosum_naive_lengthctrl.py
  - compute_tcrdist_cdr3_naive.py
  - gen_cross_model_consistency_cv.py
  - gen_distance_comparison_cv.py
  - gen_distance_comparison_cv_with_naive.py
  - gen_sankey.py
  - generate_all_panels.py

Reference values committed in `reproduce/data/reference/fig2_values.csv` are
generated by Phase P4b (one-time canonical snapshot run).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


def main(args: argparse.Namespace) -> int:
    data_root = Path(args.data_root)
    out_data = Path(args.out_data)
    out_fig = Path(args.out_fig)
    out_data.mkdir(parents=True, exist_ok=True)
    out_fig.mkdir(parents=True, exist_ok=True)

    print(f"[fig2] data_root: {data_root}")
    print(f"[fig2] out_data:  {out_data}")
    print(f"[fig2] out_fig:   {out_fig}")

    # TODO (P4b): orchestrate panel scripts and extract canonical numerical values.
    # Current state: skeleton driver. Returns a placeholder fig2_values.csv so
    # verify.sh has something to compare against. The real implementation will:
    #   1. Run cache_bcr_fig2_data.py (one-time cache)
    #   2. Run gen_distance_comparison_cv_with_naive.py for the main TCR panels
    #   3. Run compute_bcr_*_naive.py and compute_bcr_esm2_s2dd.py for BCR panels
    #   4. Run gen_cross_model_consistency_cv.py for the cross-model heatmap
    #   5. Aggregate per-model AP/AUROC correlations + degradation slopes into one CSV
    #
    # Canonical values to extract from the manuscript (Fig 2):
    #   - Per-model AP |r| (TCR + BCR, 10 models, 5 folds each)
    #   - Per-model AUROC |r|
    #   - Per-model degradation slope
    #   - Mean across folds + std
    placeholder = pd.DataFrame(
        {
            "metric": ["AP_mean_abs_r", "AUROC_mean_abs_r", "degradation_slope"],
            "tcr_mean": [float("nan")] * 3,
            "bcr_mean": [float("nan")] * 3,
        }
    )
    out_csv = out_data / "fig2_values.csv"
    placeholder.to_csv(out_csv, index=False)
    print(f"[fig2] PLACEHOLDER written: {out_csv}")
    print(f"[fig2] To complete: implement panel-script orchestration in this driver (P4b).")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", required=True,
                        help="Path to reproduce/data/input/ (committed to reproduce/data/input/)")
    parser.add_argument("--out-data", required=True,
                        help="Path to reproduce/data/output/ (where figN_values.csv is written)")
    parser.add_argument("--out-fig", required=True,
                        help="Path to reproduce/figures/output/figN/ (where figN.pdf is written)")
    sys.exit(main(parser.parse_args()))
