#!/usr/bin/env python3
"""fig3.py — Figure 3 driver: Method comparison (TCR cross-test + cross-validation).

Orchestrates panel-script invocations and extracts the canonical numerical
values for Figure 3. Writes:

  - {out_data}/fig3_values.csv  — numerical claims (verified by verify.sh)
  - {out_fig}/fig3.pdf           — rendered figure (cosmetic; not verified)

Panel scripts orchestrated (in `reproduce/scripts/fig3/`):
  - cache_bcr_fig3_fig4_data.py
  - compute_dataset_level_3method.py
  - generate_all_bcr_models_ct.py
  - generate_cv_scatter_pooled.py
  - generate_method_comparison_boxplot.py
  - generate_prediction_error_heatmaps.py
  - generate_subset_heatmaps_fig4.py
  - generate_tcr_ct_v27.py
  - generate_workflow_schematic.py
  - generate_remaining_panels.py

Reference values committed in `reproduce/data/reference/fig3_values.csv` are
generated by Phase P4b (one-time canonical snapshot run).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


def main(args: argparse.Namespace) -> int:
    data_root = Path(args.data_root)
    out_data = Path(args.out_data)
    out_fig = Path(args.out_fig)
    out_data.mkdir(parents=True, exist_ok=True)
    out_fig.mkdir(parents=True, exist_ok=True)

    print(f"[fig3] data_root: {data_root}")
    print(f"[fig3] out_data:  {out_data}")
    print(f"[fig3] out_fig:   {out_fig}")

    # TODO (P4b): orchestrate panel scripts and extract canonical numerical values.
    # Current state: PLACEHOLDER values from the manuscript (where known).

    # Canonical values to extract (Fig 3):
    #   - Per-method (PAPE / M-CBPE / S2DD) AUROC + AP MAE on cross-test
    #   - Cross-validation pooled scatter R^2
    #   - Per-model per-test-set error breakdown
    placeholder = pd.DataFrame({
        'method': ['PAPE', 'M-CBPE', 'S2DD'],
        'mean_AUROC_MAE': [float('nan')] * 3,
        'mean_AP_MAE': [float('nan')] * 3,
    })
    out_csv = out_data / "fig3_values.csv"
    placeholder.to_csv(out_csv, index=False)
    print(f"[fig3] PLACEHOLDER written: {out_csv}")
    print(f"[fig3] To complete: implement panel-script orchestration in this driver (P4b).")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", required=True,
                        help="Path to reproduce/data/input/ (populated by download_data.sh)")
    parser.add_argument("--out-data", required=True,
                        help="Path to reproduce/data/output/ (where figN_values.csv is written)")
    parser.add_argument("--out-fig", required=True,
                        help="Path to reproduce/figures/output/figN/ (where figN.pdf is written)")
    sys.exit(main(parser.parse_args()))
