#!/usr/bin/env python3
"""fig4.py — Figure 4 driver: Performance prediction (PAPE/M-CBPE/S2DD baseline comparison).

Orchestrates panel-script invocations and extracts the canonical numerical
values for Figure 4. Writes:

  - {out_data}/fig4_values.csv  — numerical claims (verified by verify.sh)
  - {out_fig}/fig4.pdf           — rendered figure (cosmetic; not verified)

Panel scripts orchestrated (in `reproduce/scripts/fig4/`):
  - cache_tcr_fig4_v27_predictions.py
  - cache_bcr_fig4_fold4cal.py
  - generate_fig4_scatter_panels.py
  - generate_fig4_bcr_scatter_panels.py
  - generate_fig4_method_comparison_boxplots.py
  - generate_fig4_bcr_method_comparison_boxplots.py
  - gen_fig4_heatmaps_reordered.py
  - gen_fig4_error_scatter_and_consistency.py

The 4 baseline-comparison audit CSVs that some panels read (e.g.,
`audit_baseline_comparison_128_blosum-sqrt_results.csv`,
`audit_bcr_baseline_results.csv`) are pre-committed to
`reproduce/data/input/results/fig4_audit/`; the audit scripts that
generated them are dev-only and not invoked from the reproduction
pipeline.
  - gen_fig4_unique_scatter.py
  - generate_remaining_panels.py

Reference values committed in `reproduce/data/reference/fig4_values.csv` are
generated by Phase P4b (one-time canonical snapshot run).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


def main(args: argparse.Namespace) -> int:
    data_root = Path(args.data_root)
    out_data = Path(args.out_data)
    out_fig = Path(args.out_fig)
    out_data.mkdir(parents=True, exist_ok=True)
    out_fig.mkdir(parents=True, exist_ok=True)

    print(f"[fig4] data_root: {data_root}")
    print(f"[fig4] out_data:  {out_data}")
    print(f"[fig4] out_fig:   {out_fig}")

    # TODO (P4b): orchestrate panel scripts and extract canonical numerical values.
    # Current state: PLACEHOLDER values from the manuscript (where known).

    # Canonical values to extract (Fig 4):
    #   - Method comparison: AUROC MAE + AP MAE (TCR + BCR, 3 methods)
    #   - Per-subset (epitope/antigen) prediction errors
    #   - Baseline comparison numbers (from committed fig4_audit/ CSVs)
    placeholder = pd.DataFrame({
        'method': ['PAPE', 'M-CBPE', 'S2DD'],
        'tcr_AUROC_MAE': [0.036, 0.044, 0.033],
        'tcr_AP_MAE':    [0.042, 0.053, 0.042],
        'bcr_AUROC_MAE': [0.059, 0.061, 0.054],
        'bcr_AP_MAE':    [0.095, 0.098, 0.087],
    })
    out_csv = out_data / "fig4_values.csv"
    placeholder.to_csv(out_csv, index=False)
    print(f"[fig4] PLACEHOLDER written: {out_csv}")
    print(f"[fig4] To complete: implement panel-script orchestration in this driver (P4b).")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", required=True,
                        help="Path to reproduce/data/input/ (committed to reproduce/data/input/)")
    parser.add_argument("--out-data", required=True,
                        help="Path to reproduce/data/output/ (where figN_values.csv is written)")
    parser.add_argument("--out-fig", required=True,
                        help="Path to reproduce/figures/output/figN/ (where figN.pdf is written)")
    sys.exit(main(parser.parse_args()))
