#!/usr/bin/env python3
"""fig5.py — Figure 5 driver: Bayesian recalibration (TCR + BCR, with retrospective).

Orchestrates panel-script invocations and extracts the canonical numerical
values for Figure 5. Writes:

  - {out_data}/fig5_values.csv  — numerical claims (verified by verify.sh)
  - {out_fig}/fig5.pdf           — rendered figure (cosmetic; not verified)

Panel scripts orchestrated (in `reproduce/scripts/fig5/`):
  - extract_fig5_tcr_panels.py
  - generate_fig5_new_panels.py
  - generate_bcr_ct_recalibration.py
  - generate_combined_dumbbell.py
  - gen_ap_dumbbell.py
  - gen_ece.py
  - gen_ppv_npv_curves.py
  - gen_roc_prc.py
  - gen_recal_paired_boxplot.py
  - gen_scatter_marginals.py
  - gen_subset_recal_scatter.py
  - gen_fig5_additional_panels.py
  - gen_fig5_lev_vs_blosum_recal.py
  - audit_recal_binning_comparison.py
  - generate_remaining_panels.py

Reference values committed in `reproduce/data/reference/fig5_values.csv` are
generated by Phase P4b (one-time canonical snapshot run).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


def main(args: argparse.Namespace) -> int:
    data_root = Path(args.data_root)
    out_data = Path(args.out_data)
    out_fig = Path(args.out_fig)
    out_data.mkdir(parents=True, exist_ok=True)
    out_fig.mkdir(parents=True, exist_ok=True)

    print(f"[fig5] data_root: {data_root}")
    print(f"[fig5] out_data:  {out_data}")
    print(f"[fig5] out_fig:   {out_fig}")

    # TODO (P4b): orchestrate panel scripts and extract canonical numerical values.
    # Current state: PLACEHOLDER values from the manuscript (where known).

    # Canonical values to extract (Fig 5):
    #   - Per-model ΔAUROC + ΔAP after recalibration (TCR 5 models, BCR 5 models)
    #   - Per-distance-bin ΔAUROC
    #   - Per-epitope improvement counts
    placeholder = pd.DataFrame({
        'model': ['NetTCR', 'ATM-TCR', 'BLOSUM-RF', 'ERGO-II', 'TCR-BERT',
                  'XBCR-net', 'DeepAAI', 'MambaAAI', 'MINT', 'RLEAAI'],
        'delta_AUROC': [float('nan')] * 10,
        'delta_AP': [float('nan')] * 10,
    })
    out_csv = out_data / "fig5_values.csv"
    placeholder.to_csv(out_csv, index=False)
    print(f"[fig5] PLACEHOLDER written: {out_csv}")
    print(f"[fig5] To complete: implement panel-script orchestration in this driver (P4b).")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", required=True,
                        help="Path to reproduce/data/input/ (populated by download_data.sh)")
    parser.add_argument("--out-data", required=True,
                        help="Path to reproduce/data/output/ (where figN_values.csv is written)")
    parser.add_argument("--out-fig", required=True,
                        help="Path to reproduce/figures/output/figN/ (where figN.pdf is written)")
    sys.exit(main(parser.parse_args()))
